server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /widget/ {
    alias /usr/share/nginx/html/widget/;
    try_files $uri $uri/ =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
